### ISSUE TITLE
feat(rotation): graceful recover when no next sequencer is available 

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/dymint#1021]
related to #1008

**Comment by mtsitrin** [comment]
blocked by https://github.com/dymensionxyz/research/issues/292

**Comment by omritoptix** [comment]
by halted here do you mean forced rotation halt or just no next sequencer?

**Comment by mtsitrin** [comment]
just no next sequencer.
the main point here is that the L2 state is the same as the committed state on the hub.
(unlike forced rotation, where the above is not guaranteed)

**Comment by mtsitrin** [comment]
@omritoptix I think it can be closed. 
will be handled as part of L2 rollback
