### ISSUE TITLE
Add support for celestia light client v0.15

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymint#1025]
> CELESTIA-NODE v0.15.0  - Mocha upgrade
> 
> Dear partners and node operators, We are pleased to announce a new version of celestia-node today. Please upgrade within the next 24h.
> 
> Release notes: https://github.com/celestiaorg/celestia-node/releases/tag/v0.15.0
> 
> This release breaks config, so a re-initialisation of the config is necessary. You can follow these instructions on how to do that: https://docs.celestia.org/nodes/celestia-node-troubleshooting#resetting-your-config
> 
>

**Comment by srene** [comment]
closing it since its dealt by https://github.com/dymensionxyz/dymint/pull/1056
