### ISSUE TITLE
prevention: do not accept block from someone who is not active sequencer

### ISSUE THREAD

**Issue by danwt** [dymensionxyz/dymint#1037]
It should not be possible for some third party to come and gossip bogus blocks, if they are not sequencer.

If we just check sequencer signature in validate basic IMO it might not be a good solution because it wont' play well with rotation and the receiving node not having up-to-date knowledge of latest sequencer

**Comment by omritoptix** [comment]
this should be already supported. can we close it? @danwt

**Comment by danwt** [comment]
Reopening, this needs some thought IMO

**Comment by danwt** [comment]
I think the question here is latency in knowing the most up to date sequencer

Blocked by

- https://github.com/dymensionxyz/dymint/issues/1088

Keeping open for now

**Comment by danwt** [comment]
Quote "we should validate sequencer pubkey on block against hub state upon event on each new event received from the hub "

**Comment by omritoptix** [comment]
I think this can be closed cause I blv this issue is about protecting against random party blocks and not about faulty sequecner rotation. in that case, I think that issue is covered.

**Comment by danwt** [comment]
Ok
May be we can discuss on Monday because thinking what if seq A is rotating to seq B correctly between H,H+1, but seq A gossips some blocks H+10 to another full node before the FN gets H or H+1, then the FN will have it cached

**Comment by danwt** [comment]
My point is I think it's worth due dilligence

**Comment by omritoptix** [comment]
> May be we can discuss on Monday because thinking what if seq A is rotating to seq B correctly between H,H+1, but seq A gossips some blocks H+10 to another full node before the FN gets H or H+1, then the FN will have it cached

should be covered by double signing. the node will compare local blocks with settlement and see mismatching sequencer. regarding who's to blame, I've already touched on it i blv in the detection matrix where for now the decision is to not detect the culprint (in that case sequencer A) but just indicate mismatching state upate and gossiped block. but we can discuss further on monday.
