### ISSUE TITLE
Possible incosistencies when pruning 

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymint#1039]
Quoting @srene 

>  there is a bug in the pruning which not sure it may cause some blocks are not pruned or it just cause inefficiency (ie some heights will skip pruning but it will prune later on). 2 i saw some inconsistencies about the retainheight returned but im not 100% sure abot that, maybe it was just a config issue, i have to recheck

**Comment by srene** [comment]
regarding 2), retainheight is limited by max_age_num_blocks param in consensus params. if min-retain-blocks is smaller than max_age_num_blocks, max_age_num_blocks is used to calculate retainheight.

**Comment by srene** [comment]
the bug identified in the pruning is that when there is a missing key for a specific height in the store (e.g. there is no cid stored for a specific height, which may happen) the pruning will return error and will not continue pruning.
