### ISSUE TITLE
Badger compaction memory optimization

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymint#1067]

**Comment by srene** [comment]
related issue from celestia node https://github.com/celestiaorg/celestia-node/issues/2905

**Comment by srene** [comment]
it seems is not only a problem of memory optimization but also memory leak on badger. i need to investigate more on that

**Comment by srene** [comment]
related issue from celestia node https://github.com/celestiaorg/celestia-node/issues/2905
