### ISSUE TITLE
block production not stopping after max_batch_skew

### ISSUE THREAD

**Issue by srene** [dymensionxyz/dymint#1077]
it only stops after max_batch_skew * batch_submit_bytes, but it does not accumulate batches based on time, i.e. it will not stop after max_batch_skew. * batch_submit_time without submitting batches.

**Comment by srene** [comment]
instead of estimating number of batches based on batch size, we could set up a limit based directly on bytes accumulated (e.g. max_batch_skew_bytes), or blocks, to avoid confusion in the config settings. but also it could be interesting to add a param for stopping based on time, e.g. max_batch_skew_time. e

**Comment by omritoptix** [comment]
@srene can we close this?
