### ISSUE TITLE
hub disconnect may cause sequencer submission failures

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymint#1097]
https://dymensionworkspace.slack.com/archives/C07B14VBU4T/p1727426324724159

**Comment by omritoptix** [comment]
@srene given the num blocks issue, is this still relevant or we can close it?

**Comment by omritoptix** [comment]
may be bug in the tests where the polling is not set high enough.
Either way need to make sure that the events listener is restored upon hub reconnection.

**Comment by omritoptix** [comment]
from visual analysis it seems like:
1. events are not triggered after disconnects
2. it falls back to polling, and the polling fails. Polling can fail from either a bug or just not enough time to poll in comparison to the test. 

Still under investigation.

**Comment by srene** [comment]
i think the create batch  issue will be solved after numblocks is fixed (although in some cases there was an error of missing proposer key, which im not sure why). 
However, i think there is still an edge case that may happen if restart is faster than inclusion of state update in the hub, in case of rotation. there is an issue open for that #1096

**Comment by omritoptix** [comment]
@srene can we close it?

**Comment by omritoptix** [comment]
closing as num blocks solved it
