### ISSUE TITLE
IBC fails to work after sequencer rotation

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/dymint#1134]
from the e2e tests:
```
2024-10-11 20:43:33 2024-10-11T13:43:33.433221Z dpanic  Querying block data.    {"chain_id": "rollappevm_1234-1", "height": 211, "error": "query ibc header: light provider light block: client provided bad signed header: expected validator hash of header to match validator set hash (6680D423BDF305154311F2371A8AD497CA123D4BCAC3A86F0D49A4D5ECD698E7 != 64462BBD08060EC93DC6A3F91896D1D8E60C399FCF2F164A26226248AC32EE5B)"}
```

this error cames from cometBFT `LightBlock.ValidateBasic`:
```
// make sure the validator set is consistent with the header
if valSetHash := lb.ValidatorSet.Hash(); !bytes.Equal(lb.SignedHeader.ValidatorsHash, valSetHash) {
return fmt.Errorf("expected validator hash of header to match validator set hash (%X != %X)",
	lb.SignedHeader.ValidatorsHash, valSetHash,
)
}
```

where the `lb.ValidatorSet` is set by:
```
res, err := p.client.Validators(ctx, height, &page, &perPage)
valSet, err := types.ValidatorSetFromExistingValidators(vals)
```

so in tendermint the header expects `ValidatorsHash`, while in dymint we set `ValidatorHash` (single propser vs the set)

------

we should either:
1. return single sequencer (the proposer) in the `p.client.Validators` API
or
2. relay on synced sequencerSet across dymint (using consensusMsg) and set the header field in compatibility with tendermint

**Comment by danwt** [comment]
1 sounds more natural to me

**Comment by danwt** [comment]
should have fixed it: https://github.com/dymensionxyz/dymint/pull/1159

**Comment by danwt** [comment]
reopened based on duc "Client expired after sequencer rotation.". Awaiting more info

**Comment by mtsitrin** [comment]
I think it might be related to the fact we store the sequencers **after** we apply the block
so for height H, we store the proposer for H+1
see this comment (https://github.com/dymensionxyz/dymint/pull/1163#discussion_r1816893443)

**Comment by danwt** [comment]
> I think it might be related to the fact we store the sequencers after we apply the block

If that's the case it seems like more your realm @mtsitrin since not directly ibc related. But LMK if that changes

**Comment by danwt** [comment]
e2e test now passing with newest relayer
