### ISSUE TITLE
full-nodes should stop processing blocks when unhealthy 

### ISSUE THREAD

**Issue by srene** [dymensionxyz/dymint#1157]
right now nodes are marked as unhealthy when e.g ValidateConfigWithRollappParams fails (because rollapp params changed) inside the applyBlock function (also upon fraud and possibly other reasons) . 
in the case of the sequencer is not a problem because the produced loop will exit and will stop producing blocks.
however for full-node nothing prevents them to continue processing blocks, and it maybe the case that new blocks are received and applied with the wrong version, leading to an invalid state.

**Comment by omritoptix** [comment]
private case of full node unhealthy?
