### ISSUE TITLE
consensus msgs requires block production 

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymint#1262]
Currently consensus msgs require block production to be applied.
by default blocks are only produced if 1hr has passed or txs are present. 

One UX problem that surfaced is for example when a sequencer updates his relayer addresses, but this change doesn't reflect in the rollapp. this is not obvious from sequencer prespective a block must be produced or he needs to wait for 1hr. 

We need to think of the best way to attack with currently few options in mind:
1. trigger block production upon new consensus msg creation 
3. handle it by an external client (e.g roller)

**Comment by keruch** [comment]
List of corner cases: https://www.notion.so/dymension/UpsertSequencer-consensus-msg-corner-cases-150a4a51f86a800caaa3fcd8d3a33adb?pvs=4

**In-memory set, Store set, Rollapp set** columns reflect the state before the next block is to be applied.

| Scenario                                                                                                 | Reboot | In-memory set | Store set  | Rollapp state | Produce next empty block                                                                                               |
|----------------------------------------------------------------------------------------------------------|--------|---------------|------------|---------------|------------------------------------------------------------------------------------------------------------------------|
| Fail before SnapshotSequencerSet                                                                         | True   | Height N+1    | Height N   | Height N      | True. There is a diff between memory and store.                                                                        |
| Fail after SnapshotSequencerSet, before block is created  (unrecoverable err; no recoverable in between) | True   | Height N+1    | Height N   | Height N      | True. There is a diff between memory and store.                                                                        |
| Fail after block is created, before block commit  (unrecoverable err; no recoverable in between)         | True   | Height N+1    | Height N   | Height N      | True. There is a diff between memory and store.                                                                        |
| Fail after block commit, before m.Store commit  (unrecoverable err; no recoverable in between)           | True   | Height N+1    | Height N   | Height N+1    | True. There is a diff between memory and store. However, the Rollapp state is updated. Duplicated consensus msgs case. |
| Fail after m.Store commit  (unrecoverable err)                                                           | True   | Height N+1    | Height N+1 | Height N+1    | False. Set is already commited to the rollapp, don't need to intentionally create an empty block.                      |
| Fail after m.Store commit  (recoverable err)                                                             | False  | Height N+1    | Height N+1 | Height N+1    | False. Set is already commited to the rollapp, don't need to intentionally create an empty block.                      |
| Success                                                                                                  | False  | Height N+1    | Height N+1 | Height N+1    | False. Set is already commited to the rollapp.                                                                         |
