### ISSUE TITLE
Create a docker compose for running a rollapp network 

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymint#138]
## Overview
For testing purposes, we want an easy way to start a rollapp network with multiple peers where currently one is pre-selected to be the aggregator/sequencer and the rest are non-aggregator nodes syncing from the sequencer.

**Comment by shaolin-flow** [comment]
This is needed for the testnet. The RDK should have Wasm so developers can test deployment and functionality of a CosmWasm smart contract on a RollApp.

**Comment by shaolin-flow** [comment]
@omritoptix can we close this as completed?
