### ISSUE TITLE
Add support for block pruning  

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymint#234]

**Comment by mtsitrin** [comment]
tendermint has the following code:
```
func (cs *State) pruneBlocks(retainHeight int64) (uint64, error) {
	base := cs.blockStore.Base()
	if retainHeight <= base {
		return 0, nil
	}
	pruned, err := cs.blockStore.PruneBlocks(retainHeight)
	if err != nil {
		return 0, fmt.Errorf("failed to prune block store: %w", err)
	}
	err = cs.blockExec.Store().PruneStates(base, retainHeight)
	if err != nil {
		return 0, fmt.Errorf("failed to prune state database: %w", err)
	}
	return pruned, nil
}
```

the `retainHeight` is calculated and received from the app in the `Commit` phase

**Comment by mtsitrin** [comment]
needs to be tested

set `min-retain-blocks` 
and check the storage size
`du -h -d 1 ~/.rollapp_evm/data/ 2>/dev/null`

**Comment by mtsitrin** [comment]
Tested this feature locally. Seems to work.
Blocks are pruned. Rollapp successfully restarts.

Anyway, I wouldn't enable this feature until actually required.
