### ISSUE TITLE
Send the abci  app the current active sequencer set

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymint#280]
Currently dymint sends nil sequencer set to the abci app and the abci app uses genesis in order to populate it's sequencer. 
The abci app should always get it's sequencer set from dymint (including genesis stage) 

### Dependencies

- [x] https://github.com/dymensionxyz/dymension-rdk/issues/132

**Comment by mtsitrin** [comment]
@omritoptix  Can be closed?
The `sequencer pubkey` read from the hub and the address on the rollapp chain set on rolalpp's genesis

Not sure we need to pass the sequencer address from the hub

**Comment by omritoptix** [comment]
The main reason I think it makes sense to pass it from the hub is incase there is a sequencer update (i.e address needs to also change) or alternatively the same sequencer wants to change the rewards address.

Not sure then how would the new/existing sequencer add the new address to the app for rewards (as it's registered in genesis).

Also I think it's cleaner to decouple it totally and not have part of the sequencer info (i.e rewards address) registered on the app and part (i.e pubkey) in the hub. 

WDYT.

**Comment by mtsitrin** [comment]
Well, I think decoupling is achieved actually in the opposite direction, by letting the rollapp set the sequencer address on the rollapp chain.
Hub manages `sequencer hub address <--> dymint pubkey`
and rollapp manages `sequencer rollapp address <--> dymint pubkey`


Anyway, this change is quite complex.
I think we definitely can live with the current state.
For additional sequencers, `create-sequencer` command exists on the rollapp
(so the rollapp operator will call `create-sequencer` on the rollapp and `create-sequencer` on the hub)

We can also use the sequencer address on the hub as the default address on the rollapp if explicit sequencer address not provided
