### ISSUE TITLE
hub rpc types coupling

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymint#281]
### Overview
Currently we are importing the types from dymension directly for interacting with it using RPC. Ideally we would like to get the protobuf of dymension and create the relevant types on our side as it creates cleaner decoupling and doesn’t rely on changes done to dymension types which are not necessarily exposed via API .

### Known issues
Trying to  change the types to not use dymension caused an issue (problem with repalcing `grpc1` to `grpc` in generated buff files)

**Comment by mtsitrin** [comment]
dup of #120
