### ISSUE TITLE
block batch submission should be determined by max batch size or max hub blocks

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymint#324]
The batch size should only be set by the number of bytes regardless to the number of blocks.
it causes confusion by having 2 different params controlling essentially the same result.

**Comment by mtsitrin** [comment]
MAX BYTES is used as the MAX limit

Batch submission should have some minimum enforcement as well
(otherwise, u can't predict when the batch will reach its max size and will be sent)

Currently, the number of blocks per batch is used as "minimum" enforcement
When empty blocks will be handled, and some minimal block time interval will take place, we could remove the number of blocks 

@omritoptix WDYT?

**Comment by omritoptix** [comment]
update the title to reflect the latest discussion in the subject.
Batch submission should be either when reaching max bytes or alternatively the time (possibly measured by hub blocks) since last batch submission > threshold.

**Comment by mtsitrin** [comment]
Using the max bytes as a trigger to submit is major effort
as it requires keeping the accumulated size and refactors throughout the code

I suggest leaving it as now:
* assuming mostly empty blocks -> the submission interval will be capped by the `submissionTimeout`
* assuming many txs and large blocks -> submission interval will be `batch size` * `block time`

so we have a guarantee of
`batch size` * `block time` < submit interval < `submissionTimeout`


I'm not sure an enhancement beyond it is worth the `High` priority now

**Comment by mtsitrin** [comment]
related to #418

**Comment by omritoptix** [comment]
this becomes a priority since we can relay on interval for the following reasons:

### KPIS
1. keep SL synced (max 1 batch behind) for syncing from DA purposes 
2. keep batch size ideal for DA and for pricing purposes
3. submission rate (byte/second) > creation reate (byte/second)

### Problem with batch interval

The batch time interval, since not depends on block batch size has the following problems:
1. high load +  high interval (e.g 1m40sec like default), given batch size limitation - a gap is formed with submitting to SL (i.e kpi 1 is violated)
2. low load + high interval (e.g 1m40sec) - most batches to da may contain 1 block which viloates kpi 2 
3. high load + low internal (e.g 2 sec) - will violate kip 3

In general, as the system load is ever changing, working with interval is not sustaible. hence we need to change to block size which in essence should automatically set the interval by the load.
