### ISSUE TITLE
Improved Performance in go-libp2p-kad-dht: New Feature Reduces PUT/Provide Latencies to <1s

### ISSUE THREAD

**Issue by dennis-tra** [dymensionxyz/dymint#350]
Hi Dymint Devs,

This is Dennis from Protocol Labs. I wanted to inform you about an exciting update regarding the [`go-libp2p-kad-dht`](https://github.com/libp2p/go-libp2p-kad-dht) implementation, which I believe you are currently using. As part of our continuous efforts to enhance performance, we have introduced a new experimental feature that significantly improves the PUT/Provide latencies.

Previously, the DHT's PUT performance was known to be rather sluggish, often taking more than 10 seconds or even minutes. However, with the latest release of `go-libp2p-kad-dht` >v0.23.0, we have introduced a feature called "Optimistic Provide" [[Kubo documentation](https://github.com/ipfs/kubo/blob/master/docs/experimental-features.md#optimistic-provide)]. This feature has demonstrated great results, bringing the latencies down to less than 1 second in the 50th percentile and less than 1.4 seconds in the 90th percentile.

While I'm unaware of the specific requirements of your use case or whether the previous latencies posed any challenges for you, I wanted to ensure that you are aware of this improvement.

If you have any questions or would like more information about this new feature, please don't hesitate to reach out.

Cheers,
Dennis

**Comment by dennis-tra** [comment]
Hi @omritoptix, have you had a chance to take a look? We've gathered some recent numbers where we found sub-second latencies from central Europe and North America. You're best to know if dymint could benefit from this and I just want to make sure you're aware 👍

**Comment by omritoptix** [comment]
Thanks! not yet unfortunately.

**Comment by srene** [comment]
Hi @dennis-tra. Are the performance improvement also affecting GET operations, or only PUT? I'm not sure whether in our case, that we use Kad DHT only for node discovery, we can benefit from the performance improvements. Is there any new parameters we need to add when setting up the DHT to enable the modifications, or it's just a matter of upgrading the DHT version? Thanks

**Comment by omritoptix** [comment]
closing as stale
