### ISSUE TITLE
Add validation for block inclusion when using celestia

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymint#422]
Celestia requires to manually call the block inclusion proof api to prove a block is available. 
Currently we ignore this step and assume it's included.

Blocked by #398

**Comment by mtsitrin** [comment]
@omritoptix can u refer to their documentation for this?
e.g Rollkit has nothing regarding this

**Comment by omritoptix** [comment]
I believe we need to run this 2: 
https://node-rpc-docs.celestia.org/?version=v0.12.2#blob.GetProof
https://node-rpc-docs.celestia.org/?version=v0.12.2#blob.Included
