### ISSUE TITLE
Problem: RPC becomes 503 always

### ISSUE THREAD

**Issue by VictorTrustyDev** [dymensionxyz/dymint#454]
There are some point of time, whenever I query something via RPC endpoint (26657), I always get this:
> node is unhealthy: Failed broadcasting tx: Priority is too low: (187 vs 187)

Look like when node is unhealthy, every other queries will be rejected

I dont know where this message came from, dymint? Isn't it?

**Comment by mtsitrin** [comment]
It's done by dymint when it enters unhealthy state
it stops producing blocks and sets the RPC to 503

**Comment by VictorTrustyDev** [comment]
@mtsitrin ok so 503 means no new block?

The problem I'm facing is I can not fetch new blocks for the block explorer.
If 503 means no new block, then no block needed to fetch, it's acceptable behavior in my side, atm.

**Comment by mtsitrin** [comment]
will be handled by #576
