### ISSUE TITLE
possible log bloat due log of the events module 

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymint#485]

**Comment by omritoptix** [comment]
Seems like the events module is logging every event reached. When talking about ABCI_QUERY with a lot of channels this makes the log very bloated.

Attached log message from the events module (which repeats very often). it's size is 168kb.

**Comment by mtsitrin** [comment]
I'll check it
maybe we should have a default `info` instead of `debug` for the roller

**Comment by omritoptix** [comment]
I think for the incentivized testnet we should keep it as debug. also this specific log message is the exception (as anyway most rollapps have low traffic/long empty block time,  so debug shouldn't be a problem)

**Comment by omritoptix** [comment]
Attaching another log file here. We should make sure that the debug log makes sense and remove the fat log messages which aren't necessary. Mostly abci query related.
