### ISSUE TITLE
GossipSub default configurations

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymint#521]
We need to set the default configuration for our gossip sub to make sure it balances between latency and throughput and is able to recover network failures

**Comment by srene** [comment]
The research paper https://www.notion.so/dymension/Rapid-Block-propagation-Mechanism-2e255ce882764cf1a4c0c3dc24ea9814?pvs=4 includes the selection of configuration parameters evaluated with the network simulator. Now it needs to be validated using testground with the real gossipsub implementation

**Comment by srene** [comment]
https://www.notion.so/dymension/Rapid-Block-propagation-Mechanism-2e255ce882764cf1a4c0c3dc24ea9814?pvs=4 includes validation of network performance and gossipsub parameters using Dymint nodes.
This PR adds the default gossipsub configuration values https://github.com/dymensionxyz/dymint/pull/540
