### ISSUE TITLE
Stopped block production is immediately resumed after receiving a health status event from the data availability or settlement layer

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymint#659]

**Comment by danwt** [comment]
Spoke on call, we decided we ought to improve the error handling in the produce loop to better deal with the following situations

- non recoverable error
- recover with retry (produce block again)
- recover with retry (don't produce block again)


Also, the following may be fixed at the same time https://github.com/dymensionxyz/dymint/issues/654

**Comment by danwt** [comment]
Also to tackle at same time: https://github.com/dymensionxyz/dymint/issues/618
