### ISSUE TITLE
dymint node crashes after waiting celestia light node for syncing

### ISSUE THREAD

**Issue by srene** [dymensionxyz/dymint#669]
node crashes with following errorwhen it has to wait for celestia light node to finish syncing

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x40 pc=0x10671aa28]

goroutine 406 [running]:
github.com/dymensionxyz/dymint/da/celestia.(*DataAvailabilityLayerClient).submit(0x14000d12460, {0x14007e08a00?, 0x140090b9cf8?, 0x0?})
	/Users/sergi/workspace/dymension/dymint/da/celestia/celestia.go:558 +0x218
github.com/dymensionxyz/dymint/da/celestia.(*DataAvailabilityLayerClient).SubmitBatch(0x14000d12460, 0x10677af94?)
	/Users/sergi/workspace/dymension/dymint/da/celestia/celestia.go:217 +0x1d0
github.com/dymensionxyz/dymint/block.(*Manager).submitNextBatch(0x14005f18008, {0x107f02920?, 0x109c961e0?})
	/Users/sergi/workspace/dymension/dymint/block/submit.go:89 +0x3ac
github.com/dymensionxyz/dymint/block.(*Manager).SubmitLoop(0x14005f18008, {0x107f02920, 0x109c961e0})
	/Users/sergi/workspace/dymension/dymint/block/submit.go:46 +0x224
created by github.com/dymensionxyz/dymint/block.(*Manager).Start in goroutine 58
	/Users/sergi/workspace/dymension/dymint/block/manager.go:187 +0x378

**Comment by mtsitrin** [comment]
can be closed?

**Comment by srene** [comment]
yes. i think it was solved in https://github.com/dymensionxyz/dymint/pull/857
