### ISSUE TITLE
nodes should not panic when unable to connect to DA light client

### ISSUE THREAD

**Issue by srene** [dymensionxyz/dymint#772]
it maybe they are able to sync from P2P without DA, so i would retry instead of panic when failing syncuntiltarget from DA

**Comment by danwt** [comment]
related? https://github.com/dymensionxyz/dymint/issues/770

**Comment by danwt** [comment]
@srene same as #770?

**Comment by srene** [comment]
fixed in https://github.com/dymensionxyz/dymint/pull/857
