### ISSUE TITLE
consensus gov params don't effect dymint after genesis

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymint#791]
Not sure this should be fixed. depends on the outcome of : https://github.com/dymensionxyz/research/issues/271

**Comment by srene** [comment]
https://www.notion.so/dymension/Rollapp-Consensus-params-fef656eb16464dbfaac0eb13e34a27d5?pvs=4

**Comment by omritoptix** [comment]
related: https://www.notion.so/dymension/Rollapp-Social-Consensus-Params-c848193f0c254628bd9ebbe2d5449549

**Comment by omritoptix** [comment]
closing this as we're gonna move those params to be consensus params.
