### ISSUE TITLE
add the option to sync a node from p2p as primary source

### ISSUE THREAD

**Issue by srene** [dymensionxyz/dymint#805]

**Comment by omritoptix** [comment]
blocked by https://github.com/dymensionxyz/research/issues/272

**Comment by omritoptix** [comment]
Adding reasoning about the importance of it:
1. for rpc nodes who don't want to validate data from Celestia it will provide with it much faster syncing ability (after e.g syncing from snapshot) until it's synced in real time
1. In case the da is down/light client is not responsive, there is no dependency on it.
