### ISSUE TITLE
`namespaceID` as a block field is probably redundent

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/dymint#806]
Currently, besides the DA's namespace param, which used for blob submission,
we also have `Namespace` field in the block itself.

Seems redundant and unused

**Comment by mtsitrin** [comment]
@srene do u think it can be removed or we missing something?

**Comment by srene** [comment]
it do not see any reason why we need a namespace_id param in the block manager. for da submission it is used the namespace id param from da_config only.

**Comment by srene** [comment]
The namespaceid config parameter is as field used in the block manager, that is actually included in every block header. I would not remove it by now, since modifying header fields can be a critical update

**Comment by mtsitrin** [comment]
well we can leave it in the header type, just not fill it if it's unused
