### ISSUE TITLE
multiple `AccumulatedData` in case of submission latency

### ISSUE THREAD

**Issue by mtsitrin** [dymensionxyz/dymint#954]
The `AccumulatedBatchSize` is cleared on submission iteration.

When `m.AccumulatedBatchSize` has reached the max, it will trigger `toSubmit` event for each subsequent block, until the submission handler iterates again.

**Comment by danwt** [comment]
In other words:
there is a loop which tracks accumulated data and submits signals whenever the accumulated mount is exceeded, but the counter is is not set to zero when submitting the signal, but rather, when consuming it
