### ISSUE TITLE
Failed to prune blocks though height is already submitted

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/dymint#994]
When trying to prune blocks on mainnet we've got the following error: 

`[31mERRO[0m[0033] prune blocks[retain_height 517071 err cannot prune blocks before they have been submitted: 517071: invalid argument]  [31mmodule[0m=BlockManager`

This is despite the fact that the latest submitted height was much higher

`[36mINFO[0m[0032] Synced.[current height 617070 last submitted height 617035]  [36mmodule[0m=BlockManager`

[https://grafana.mainnet.noisnemyd.xyz/explore?schemaVersion=1&panes=%7B%22xdf%22:%7B%22data[…]om%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&orgId=1](https://grafana.mainnet.noisnemyd.xyz/explore?schemaVersion=1&panes=%7B%22xdf%22:%7B%22datasource%22:%22ddl6j61t39fy8b%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%22ra-mainnet-nim-evm-sequencer%5C%22%7D%20%7C%3D%20%60prune%60%20or%20%60batch%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22ddl6j61t39fy8b%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D%7D&orgId=1)

**Comment by omritoptix** [comment]
Attached all-in-bets log: 
[log4.txt](https://github.com/user-attachments/files/16487950/log4.txt)

**Comment by mtsitrin** [comment]
seems to be fixed by #966
